version: '2'
services:
  mysql:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    container_name: javatest3_mysql_1

  jdk:
    image: java
    depends_on:
      - mysql
    environment:
      - name=root
      - pwd=123456
      - ip=192.168.99.100
      - port=3306
      - dbname=sakila
      - country_id=2
      - customer_id=1
    container_name: javatest3_jdk_1